### ISSUE TITLE
Fix total game counting in results

### ISSUE THREAD

**Issue by climu** [PatrickJAMET/ASR#4]
The results appear not to count the total number of game in each class effectively.

For instance, in alpha, with 8 players playing 2 games with each others, I guess the total number of games should be 8*7*2=112 while the website count half of it.

It must be somewhere in [leaguelib.php](https://github.com/PatrickJAMET/ASR/blob/master/asrleague/leaguelib.php)

**Comment by PatrickJAMET** [comment]
Yes it seems that there is a double foreach to compute this value then the total is divided by 2.. line 442.

maybe remove the double foreach and the line 442 and replace it by something like:
`$size = sizeof($rco['participants']);
$total = $size*($size-1)*2;`

**Comment by climu** [comment]
Hum, I fear I was wrong...
Since one game count for 2 player.
I mean we only have to fill half the results table and the other half will be filled too.
Not sure I am clear.
Shame on me as a math teacher.
